#./app/config/routing.yml

    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /frais-api/doc

rest:                               # nom de la route
    type: rest 
    resource: "routing_rest.yml"
    prefix: /api
    
#./app/config/routing.yml

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
api_login_check:
    path: /api/login_check

    
